version: "3.9"

services:
  db:
    restart: always
    image: postgres:14.6-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    restart: always
    build: backend
    command:
      gunicorn star_burger.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - ./static:/opt/app/staticfiles
      - ./media:/opt/app/media
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  nginx:
    restart: always
    build: nginx_ssl
    volumes:
      - ./static:/opt/app/static
      - ./media:/opt/app/media
      - ./volume/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./volume/certbot/www/:/var/www/certbot/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./volume/certbot/www/:/var/www/certbot/:rw
      - ./volume/certbot/conf/:/etc/letsencrypt/:rw

volumes:
  static:
  media:
  db_data: