version: "3.9"

services:
  db:
    image: postgres:14.6-alpine
    # volumes:
    #   - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  backend:
    build: backend
    command:
      bash entrypoint.sh
    volumes:
      - static:/opt/app/staticfiles
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - YANDEX_API_KEY=${YANDEX_API_KEY}
      - ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - POSTGRES_DB_URL=${POSTGRES_DB_URL}
    ports:
      - "8080:8080"
    depends_on:
    #   # - nginx
    #   # - frontend
      - db

  # frontend:
  #   build: frontend
  #   volumes:
  #     - static:/opt/app/bundles
  #   command: node_modules/.bin/parcel watch ./bundles-src/index.js --dist-dir bundles --public-url "./"
  #   ports:
  #     - "1234:1234"

  # nginx:
  #   build: nginx
  #   volumes:
  #     - static:/opt/app/static
  #   ports:
  #     - "80:80"

volumes:
  static: