version: "3.9"

services:
  db:
    image: postgres:14.6-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: backend
    command:
      bash entrypoint.sh
    volumes:
      - ./backend:/opt/app
      - ./static:/opt/app/staticfiles
      - ./media:/opt/app/media
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - frontend
      - db

  frontend:
    build: frontend
    volumes:
      - ./static:/opt/app/bundles
    command: node_modules/.bin/parcel watch ./bundles-src/index.js --dist-dir bundles --public-url "./"

  nginx:
    build: nginx
    volumes:
      - ./static:/opt/app/static
      - ./media:/opt/app/media
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  static:
  media:
  db_data: