version: "3.9"

services:
  db:
    restart: always
    image: postgres:14.6-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    restart: always
    build: backend
    command:
      gunicorn star_burger.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - ./static:/opt/app/staticfiles
      - ./media:/opt/app/media
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  nginx:
    image: staticfloat/nginx-certbot
    volumes:
      - static_volume:/opt/static
      - media_volume:/opt/media
      - ./nginx_ssl:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    env_file:
      - .env
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - web

volumes:
  static:
  media:
  db_data:
  letsencrypt: