# Generated by Django 3.2.15 on 2023-02-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_productinorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Необработанный', 'Необработанный'), ('Готовится', 'Готовится'), ('Отправлен', 'Отправлен'), ('Выполнен', 'Выполнен')], db_index=True, default='Необработанный', max_length=14, verbose_name='Статус заказа'),
        ),
    ]
