# Generated by Django 3.2.15 on 2023-02-18 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_restaurant', to='foodcartapp.restaurant', verbose_name='ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Электронно'), ('CASH', 'Наличностью')], db_index=True, default='Не указан', max_length=14, verbose_name='Способо оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RAW', 'Необработанный'), ('PREPARE', 'Готовится'), ('SENT', 'Отправлен'), ('COMPLETED', 'Выполнен')], db_index=True, default='Необработанный', max_length=14, verbose_name='Статус заказа'),
        ),
    ]
