# Generated by Django 3.2.15 on 2023-01-31 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_productinorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Продукт в заказе', 'verbose_name_plural': 'Продукты в заказе'},
        ),
    ]
