# Generated by Django 3.2.15 on 2023-02-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20230214_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Наличностью', 'Наличностью'), ('Электронно', 'Электронно')], db_index=True, default='Наличностью', max_length=14, verbose_name='Способо оплаты'),
        ),
    ]
