# Generated by Django 3.2.15 on 2023-03-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20230220_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='registrated_at',
            new_name='registered_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Электронно'), ('CASH', 'Наличностью')], db_index=True, default='Не указан', max_length=14, verbose_name='Способ оплаты'),
        ),
    ]
